// <auto-generated />
using System;
using GalaxyControl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalaxyControl.Migrations
{
    [DbContext(typeof(GalaxyControlContext))]
    [Migration("20241021143618_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GalaxyControl.Models.Nave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Armamento")
                        .HasColumnType("int")
                        .HasColumnName("armamento");

                    b.Property<string>("CodigoRastreio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo_rastreio");

                    b.Property<int>("Cor")
                        .HasColumnType("int")
                        .HasColumnName("cor");

                    b.Property<DateTime>("DataQueda")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_queda");

                    b.Property<int>("GrauAvaria")
                        .HasColumnType("int")
                        .HasColumnName("grau_avaria");

                    b.Property<int>("GrauPericulosidade")
                        .HasColumnType("int")
                        .HasColumnName("grau_periculosidade");

                    b.Property<string>("LocalQueda")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("local_queda");

                    b.Property<int>("PotencialProspeccaoTecnologica")
                        .HasColumnType("int")
                        .HasColumnName("potencial_prospeccao_tecnologica");

                    b.Property<int>("Tamanho")
                        .HasColumnType("int")
                        .HasColumnName("tamanho");

                    b.Property<int>("TipoCombustivel")
                        .HasColumnType("int")
                        .HasColumnName("tipo_combustivel");

                    b.Property<int>("TipoLocalQueda")
                        .HasColumnType("int")
                        .HasColumnName("tipo_local_queda");

                    b.HasKey("Id");

                    b.ToTable("nave", (string)null);
                });

            modelBuilder.Entity("GalaxyControl.Models.Tripulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<int>("NaveId")
                        .HasColumnType("int")
                        .HasColumnName("id_nave");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("NaveId");

                    b.ToTable("tripulante", (string)null);
                });

            modelBuilder.Entity("GalaxyControl.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCadastro = new DateTime(2024, 10, 21, 11, 36, 17, 12, DateTimeKind.Local).AddTicks(9014),
                            Email = "galaxycontrol@outlook.com",
                            Login = "admin",
                            Nome = "Admin",
                            Senha = "7110eda4d09e062aa5e4a390b0a572ac0d2c0220"
                        });
                });

            modelBuilder.Entity("GalaxyControl.Models.Tripulante", b =>
                {
                    b.HasOne("GalaxyControl.Models.Nave", "Nave")
                        .WithMany("Tripulante")
                        .HasForeignKey("NaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nave");
                });

            modelBuilder.Entity("GalaxyControl.Models.Nave", b =>
                {
                    b.Navigation("Tripulante");
                });
#pragma warning restore 612, 618
        }
    }
}
